### ISSUE TITLE
Build fails with Go 1.27

### ISSUE THREAD

**Issue by stefanb** [pingcap/tidb#70069]
Hey,

build with Go 1.27 fails with `pkg/util/hack/hack.go:41:2: undefined: checkMapABI`

...due to unmet `!go1.27` build constraints:
https://github.com/pingcap/tidb/blob/05b396fb6636f73b3bc06b09107cf43f2c725c35/pkg/util/hack/map_abi_go126.go#L15
https://github.com/pingcap/tidb/blob/05b396fb6636f73b3bc06b09107cf43f2c725c35/pkg/util/hack/map_abi_test_type_go126_test.go#L15
https://github.com/pingcap/tidb/blob/05b396fb6636f73b3bc06b09107cf43f2c725c35/pkg/util/hack/map_abi_test.go#L15

Found in 
* https://github.com/Homebrew/homebrew-core/pull/288803
